### ISSUE TITLE
Remove   "nikic/php-parser": "^1.4" dependency 

### ISSUE THREAD

**Issue by krewetka** [bresam/ivory-serializer#2]
@bresam  I know that you might not have time but would be great if you could check if we can remove this really outdated dependency :thinking: 

And this one is blocking updating other packages where many of them require versions 3 or 4 already.

I have checked and I don't see any use of anything from namespace `PhpParser` or any use of `php-parser` binary.

Would be great if you could double check it and then we could simple remove it from composer.json.

**Comment by bresam** [comment]
Hi @krewetka 

It seems you are right, unittests also work still fine.
I've removed that dependency.

Feel free to create a PR next time.

Best Samuel

**Comment by krewetka** [comment]
Yeap, next time I will create PR. 

Just wasn't 100% sure if I am right ;)

Thanks for really quick response.

Btw, it looks like travis tests are failing due to PHPUnit_Framework_TestCase which is not working anymore in phpunit 6

**Comment by bresam** [comment]
Yes i know, i hadn't the time to update these unittests yet.

**Comment by krewetka** [comment]
Sure, no problem. Btw I recently fixed this kind of issue in my project by find and replace ;)
